# Local Kafka (docker-compose fast_layer.yml) — DEV environment
# Used instead of MSK in local development
NETWORK=mainnet
KAFKA_BROKERS=kafka-broker-1:9092
SCHEMA_REGISTRY_URL=http://schema-registry:8081
