
x-common-log-config: &default_config
  networks:
    - ice_lakehouse_dev

x-common-healthcheck-default: &default_healthcheck
  timeout: 45s
  interval: 10s
  retries: 10
  start_period: 10s


services:

  minio:
    image: bitnami/minio:2024.9.22
    container_name: minio
    env_file:
      - ./conf/spark_str_bronze_multiplex.conf
      - ./conf/.secrets.conf
    <<: *default_config
    volumes:
      - ice_lakehouse_minio_dev_vol:/bitnami/minio/data
    ports:
      - 9001:9001


  postgres_nessie:
    image: postgres:16
    container_name: postgres_nessie
    environment:
      POSTGRES_USER: nessie
      POSTGRES_PASSWORD: nessie
      POSTGRES_DB: nessie
    volumes:
      - ice_lakehouse_pg_nessie_dev_vol:/var/lib/postgresql/data
    <<: *default_config


  nessie:
    image: bitnami/nessie:0.99.0
    container_name: nessie
    restart: always
    <<: *default_config
    environment:
      - NESSIE_VERSION_STORE_TYPE=JDBC
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres_nessie:5432/nessie
      - QUARKUS_DATASOURCE_USERNAME=nessie
      - QUARKUS_DATASOURCE_PASSWORD=nessie
    ports:
      - 19120:19120
    depends_on:
      - postgres_nessie

  # dremio:
  #   image: dremio/dremio-oss:25.1
  #   ports:
  #     - 9047:9047
  #   container_name: dremio
  #   volumes:
  #     - ice_lakehouse_dremio_dev_vol:/opt/dremio/data
  #   <<: *default_config

volumes:
  ice_lakehouse_minio_dev_vol:
  ice_lakehouse_dremio_dev_vol:
  ice_lakehouse_pg_nessie_dev_vol:

networks:
  ice_lakehouse_dev:
    name: ice_lakehouse_dev