version: "3"

##########################################################################################
#########################    DEPLOYMENT CONFIGS FOR NODES    #############################

x-common-deploy-master: &common_deploy_master
  deploy:
    restart_policy:
      condition: on-failure
    placement:
      constraints: [node.hostname == dadaia-desktop]

x-common-deploy-worker-1: &common_deploy_worker_1
  deploy:
    restart_policy:
      condition: on-failure
    placement:
      constraints: [node.hostname == dadaia-HP-ZBook-15-G2]

x-common-deploy-worker-2: &common_deploy_worker_2
  deploy:
    restart_policy:
      condition: on-failure
    placement:
      constraints: [node.hostname == dadaia-server-2]

##########################################################################################
#############################    SERVICES    #############################################

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zookeeper
    restart: always
    networks:
      - vpc_dm
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_JMX_PORT: 9101
    volumes:
    - type: volume
      source: swarm_zookeeper_data
      target: /var/lib/zookeeper/data
    - type: volume
      source: swarm_zookeeper_log
      target: /var/lib/zookeeper/log
    - type: volume
      source: swarm_zookeeper_secrets
      target: /etc/zookeeper/secrets
    <<: *common_deploy_worker_1

  broker-1:
    image: confluentinc/cp-server:7.6.0
    hostname: broker-1
    restart: on-failure
    networks:
      - vpc_dm
    ports:
      - "7071:7071"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 7071
      KAFKA_JMX_HOSTNAME: localhost
      #KAFKA_OPTS: "-javaagent:/opt/jmx_exporter/jmx_prometheus_javaagent.jar=7071:/opt/jmx_exporter/kafka-metrics.yml"
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-1:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    volumes:
    - type: volume
      source: swarm_broker_1_data
      target: /var/lib/kafka/data
    - type: volume
      source: swarm_broker_1_secrets
      target: /etc/kafka/secrets
    <<: *common_deploy_worker_1


  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    hostname: schema-registry
    restart: always
    networks:
      - vpc_dm
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker-1:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_SCHEMA_COMPATIBILITY_LEVEL: FULL
    <<: *common_deploy_worker_1


  control-center:
    image: confluentinc/cp-enterprise-control-center:7.6.0
    hostname: control-center
    restart: always
    networks:
      - vpc_dm
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker-1:29092'
      #CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      #CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      #CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    <<: *common_deploy_worker_1


  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.5.0
    networks:
      - vpc_dm
    ports:
      - 8082:8082
    hostname: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker-1:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
    <<: *common_deploy_worker_1
    
  redis: 
    image: redis:7.2
    networks:
    - vpc_dm
    command: redis-server --requirepass secret
    ports:
      - "16379:6379"
    <<: *common_deploy_worker_1


      
volumes:
  swarm_zookeeper_data:
  swarm_zookeeper_log:
  swarm_zookeeper_secrets:
  swarm_broker_1_data:
  swarm_broker_1_secrets:

networks:
  vpc_dm:
    external: true


