version: "3"


##########################################################################################
#########################    DEPLOYMENT CONFIGS FOR NODES    #############################

x-swarm-master-node: &swarm_master_node
  placement:
    constraints: [node.hostname == dadaia-desktop]

x-swarm-worker-1: &swarm_worker_1
  placement:
    constraints: [node.hostname == dadaia-HP-ZBook-15-G2]

x-swarm-worker-2: &swarm_worker_2
  placement:
    constraints: [node.hostname == dadaia-server-2]

x-swarm-worker-3: &swarm_worker_3
  placement:
    constraints: [node.hostname == dadaia-server-3]

##########################################################################################
#############################    SERVICES    #############################################

services:

  minio:
    image: bitnami/minio:2024.9.22
    env_file:
      - ./conf/swarm.lakehouse.conf
      - ./conf/swarm.secrets.conf
    networks:
      - vpc_dm
    volumes:
      - swarm_minio_data:/bitnami/minio/data
    ports:
      - 9001:9001
    deploy:
      <<: *swarm_worker_2


  nessie_pg:
    image: postgres:16
    networks:
      - vpc_dm
    environment:
      POSTGRES_USER: ${PG_NESSIE_USER-nessie}
      POSTGRES_PASSWORD: ${PG_NESSIE_PASSWORD-nessie}
      POSTGRES_DB: ${PG_NESSIE_DB-nessie}
    volumes:
      - swarm_pg_nessie:/var/lib/postgresql/data
    #entrypoint: ["sleep", "infinity"]
    deploy:
      <<: *swarm_worker_2



  nessie:
    image: bitnami/nessie:0.99.0
    networks:
      - vpc_dm
    environment:
      - NESSIE_VERSION_STORE_TYPE=JDBC
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://nessie_pg:5432/${PG_NESSIE_DB-nessie}
      - QUARKUS_DATASOURCE_USERNAME=${PG_NESSIE_USER-nessie}
      - QUARKUS_DATASOURCE_PASSWORD=${PG_NESSIE_PASSWORD-nessie}
    ports:
      - 19120:19120
    deploy:
      <<: *swarm_worker_1


  dremio:
    image: dremio/dremio-oss:25.1
    networks:
      - vpc_dm
    ports:
      - 9047:9047
    volumes:
      - swarm_vol_dremio:/opt/dremio/data
    deploy:
      <<: *swarm_worker_2



volumes:
  swarm_pg_nessie:
  swarm_vol_dremio:
  swarm_minio_data:


networks:
  vpc_dm:
    external: true