version: "3"


##########################################################################################
#########################    DEPLOYMENT CONFIGS FOR NODES    #############################

x-common-deploy-master: &common_deploy_master
  deploy:
    restart_policy:
      condition: on-failure
    placement:
      constraints: [node.hostname == dadaia-desktop]

x-common-deploy-worker-1: &common_deploy_worker_1
  deploy:
    restart_policy:
      condition: on-failure
    placement:
      constraints: [node.hostname == dadaia-HP-ZBook-15-G2]

x-common-deploy-worker-2: &common_deploy_worker_2
  deploy:
    restart_policy:
      condition: any
    placement:
      constraints: [node.hostname == dadaia-server-2]

##########################################################################################
#############################    SERVICES    #############################################

services:

  minio:
    image: bitnami/minio:2024.9.22
    env_file:
      - ./conf/swarm.lakehouse.conf
      - ./conf/swarm.secrets.conf
    networks:
      - vpc_dm
    volumes:
      - swarm_minio_data:/bitnami/minio/data
    ports:
      - 9001:9001
    <<: *common_deploy_worker_2


  nessie_pg:
    image: postgres:16
    networks:
      - vpc_dm
    environment:
      POSTGRES_USER: ${PG_NESSIE_USER-nessie}
      POSTGRES_PASSWORD: ${PG_NESSIE_PASSWORD-nessie}
      POSTGRES_DB: ${PG_NESSIE_DB-nessie}
    volumes:
      - swarm_pg_nessie:/var/lib/postgresql/data
    <<: *common_deploy_worker_2

  nessie:
    image: bitnami/nessie:0.99.0
    networks:
      - vpc_dm
    environment:
      - NESSIE_VERSION_STORE_TYPE=JDBC
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://nessie_pg:5432/${PG_NESSIE_DB-nessie}
      - QUARKUS_DATASOURCE_USERNAME=${PG_NESSIE_USER-nessie}
      - QUARKUS_DATASOURCE_PASSWORD=${PG_NESSIE_PASSWORD-nessie}
    ports:
      - 19120:19120
    <<: *common_deploy_worker_2


  dremio:
    image: dremio/dremio-oss:25.1
    networks:
      - vpc_dm
    ports:
      - 9047:9047
    volumes:
      - swarm_vol_dremio:/opt/dremio/data
    <<: *common_deploy_worker_2

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    volumes:
      - "swarm_vol_dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    <<: *common_deploy_worker_2


volumes:
  swarm_pg_nessie:
  swarm_vol_dremio:
  swarm_minio_data:
  swarm_vol_dynamodb:


networks:
  vpc_dm:
    external: true