version: '3'

##########################################################################################
################    DEFAULT CONFIG FOR NODE EXPORTER AND CADVISOR    #####################

x-common-exporters-default: &node_exporter_commons
  image: quay.io/prometheus/node-exporter:latest
  networks:
    - vpc_kafka
  command:
    - '--path.rootfs=/host'
  pid: host
  volumes:
    - '/:/host:ro,rslave'

x-common-cadvisor-default: &cadvisor_commons
  image: gcr.io/cadvisor/cadvisor:v0.44.1-test
  networks:
    - vpc_kafka
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
  command:
    - '--enable_metrics=advtcp,app,cpu,cpuLoad,cpu_topology,disk,diskIO,memory,memory_numa,network'


##########################################################################################
#########################    DEPLOYMENT CONFIGS FOR NODES    #############################

x-common-deploy-master: &common_deploy_master
  deploy:
    restart_policy:
      condition: on-failure
    placement:
      constraints: [node.hostname == dadaia-desktop]

x-common-deploy-worker-1: &common_deploy_worker_1
  deploy:
    restart_policy:
      condition: on-failure
    placement:
      constraints: [node.hostname == dadaia-HP-ZBook-15-G2]

x-common-deploy-worker-2: &common_deploy_worker_2
  deploy:
    restart_policy:
      condition: on-failure
    placement:
      constraints: [node.hostname == dadaia-server-2]

##########################################################################################
################################    SERVICES CONFIG    ###################################

services:

  # PROMETHEUS UI -> http://192.168.15.101:9090
  prometheus:
    image: marcoaureliomenezes/prometheus:1.0.0
    <<: *common_deploy_worker_1
    networks:
      - vpc_kafka
    ports:
      - 9090:9090
    volumes:
      - swarm_vol_prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

        
  # GRAFANA UI -> http://192.168.15.101:13000
  grafana:
    image: grafana/grafana
    <<: *common_deploy_worker_1
    networks:
      - vpc_kafka
    ports:
      - 3000:3000
    volumes:
      - swarm_vol_grafana:/var/lib/grafana
    

  # VISUALIZER SWARM -> http://192.168.15.101:28080/
  visualizer:
    image: dockersamples/visualizer:stable
    <<: *common_deploy_master
    ports:
      - "28080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  ########################################################################################

  # Dashboard ID: 18941, 15465 Don't work 12931, 1442
  kafka-exporter:
    image: danielqsj/kafka-exporter 
    container_name: kafka-exporter
    command: ["--kafka.server=broker:29092"]
    networks:
      - vpc_kafka
    <<: *common_deploy_worker_1
    ports:
      - 9308:9308


  ########################################################################################
  #####################    MONITORING DOCKER WITH CADVISOR    ############################

  cadvisor_master:
    <<: *cadvisor_commons
    ports:
      - 38080:8080
    <<: *common_deploy_master

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 1
  cadvisor_worker_1:
    <<: *cadvisor_commons
    ports:
      - 38081:8080
    <<: *common_deploy_worker_1

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 2
  cadvisor_worker_2:
    <<: *cadvisor_commons
    ports:
      - 38082:8080
    <<: *common_deploy_worker_2

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 3
  # cadvisor_worker_3:
  #   <<: *cadvisor_commons
  #   ports:
  #     - 38083:8080
  #   <<: *common_deploy_worker_3

  ########################################################################################
  #####################    MONITORING SERVERS SWARM CLUSTER    ###########################

  node_exporter_master:
    <<: *node_exporter_commons
    <<: *common_deploy_master

  node_exporter_worker_1:
    <<: *node_exporter_commons
    <<: *common_deploy_worker_1

  node_exporter_worker_2:
    <<: *node_exporter_commons
    <<: *common_deploy_worker_2

  # node_exporter_worker_3:
  #   <<: *node_exporter_commons
  #   <<: *common_deploy_worker_3

############################    END OF SERVICES CONFIG    ################################
##########################################################################################

volumes:
  swarm_vol_prometheus:
  swarm_vol_grafana:

networks:
  vpc_kafka:
    external: true
