##########################################################################################
################    DEFAULT CONFIG FOR NODE EXPORTER AND CADVISOR    #####################

x-common-exporters-default: &node_exporter_commons
  image: quay.io/prometheus/node-exporter:latest
  networks:
    - vpc_dm
  command:
    - '--path.rootfs=/host'
  pid: host
  volumes:
    - '/:/host:ro,rslave'

x-common-cadvisor-default: &cadvisor_commons
  image: gcr.io/cadvisor/cadvisor:v0.44.1-test
  networks:
    - vpc_dm
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
  command:
    - '--enable_metrics=advtcp,app,cpu,cpuLoad,cpu_topology,disk,diskIO,memory,memory_numa,network'


##########################################################################################
#########################    DEPLOYMENT CONFIGS FOR NODES    #############################

x-swarm-master-node: &swarm_master_node
  placement:
    constraints: [node.hostname == dadaia-desktop]

x-swarm-worker-1: &swarm_worker_1
  placement:
    constraints: [node.hostname == dadaia-HP-ZBook-15-G2]

x-swarm-worker-2: &swarm_worker_2
  placement:
    constraints: [node.hostname == dadaia-server-2]

x-swarm-worker-3: &swarm_worker_3
  placement:
    constraints: [node.hostname == dadaia-server-3]

##########################################################################################
################################    SERVICES CONFIG    ###################################

services:

  # PROMETHEUS UI -> http://192.168.15.101:9090
  prometheus:
    image: marcoaureliomenezes/prometheus:1.0.0
    networks:
      - vpc_dm
    ports:
      - 9090:9090
    volumes:
      - swarm_vol_prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      <<: *swarm_worker_1
        
  # GRAFANA UI -> http://192.168.15.101:13000
  grafana:
    image: grafana/grafana
    networks:
      - vpc_dm
    ports:
      - 3000:3000
    volumes:
      - swarm_vol_grafana:/var/lib/grafana
    deploy:
      <<: *swarm_master_node
    

  # VISUALIZER SWARM -> http://192.168.15.101:28080/
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "28080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      <<: *swarm_master_node

  ########################################################################################

  # Dashboard ID: 18941, 15465 Don't work 12931, 1442
  kafka-exporter:
    image: danielqsj/kafka-exporter
    command: ["--kafka.server=broker-1:29092"]
    networks:
      - vpc_dm
    ports:
      - 9308:9308
    deploy:
      <<: *swarm_worker_1

  ########################################################################################
  #####################    MONITORING DOCKER WITH CADVISOR    ############################

  cadvisor_master:
    <<: *cadvisor_commons
    ports:
      - 38080:8080
    deploy:
      <<: *swarm_master_node

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 1
  cadvisor_worker_1:
    <<: *cadvisor_commons
    ports:
      - 38081:8080
    deploy:
      <<: *swarm_worker_1

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 2
  cadvisor_worker_2:
    <<: *cadvisor_commons
    ports:
      - 38082:8080
    deploy:
      <<: *swarm_worker_2

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 3
  cadvisor_worker_3:
    <<: *cadvisor_commons
    ports:
      - 38083:8080
    deploy:
      <<: *swarm_worker_3

  ########################################################################################
  #####################    MONITORING SERVERS SWARM CLUSTER    ###########################

  node_exporter_master:
    <<: *node_exporter_commons
    deploy:
      <<: *swarm_master_node

  node_exporter_worker_1:
    <<: *node_exporter_commons
    deploy:
      <<: *swarm_worker_1

  node_exporter_worker_2:
    <<: *node_exporter_commons
    deploy:
      <<: *swarm_worker_2

  node_exporter_worker_3:
    <<: *node_exporter_commons
    deploy:
      <<: *swarm_worker_3

############################    END OF SERVICES CONFIG    ################################
##########################################################################################

volumes:
  swarm_vol_prometheus:
  swarm_vol_grafana:

networks:
  vpc_dm:
    external: true
