spark.master=                               spark://spark-master:7077
spark.driver.memory=                        512m
spark.executor.memory=                      512m
spark.executor.cores=                       1

spark.jars.packages=org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.8,org.apache.spark:spark-avro_2.12:3.5.8,org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
spark.jars.repositories=https://repo1.maven.org/maven2

# S3A filesystem (AWS S3 checkpoint support)
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.DefaultAWSCredentialsProviderChain
spark.hadoop.fs.s3a.endpoint=s3.sa-east-1.amazonaws.com
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.connection.ssl.enabled=true
