version: '3'


x-common-exporters-default: &node_exporter_commons
  image: quay.io/prometheus/node-exporter:latest
  command:
    - '--path.rootfs=/host'
  pid: host
  volumes:
    - '/:/host:ro,rslave'
  networks:
    - dm_cluster_prod-fast


    
x-common-cadvisor-default: &cadvisor_commons
  image: gcr.io/cadvisor/cadvisor:v0.44.1-test
  networks:
    - dm_cluster_prod-fast
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  command:
    - '--enable_metrics=advtcp,app,cpu,cpuLoad,cpu_topology,disk,diskIO,memory,memory_numa,network'

x-common-restart-default: &common_restart_policy
  restart_policy:
    condition: on-failure

x-common-deploy-master: &common_deploy_master
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-desktop]

x-common-deploy-worker-1: &common_deploy_worker_1
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-HP-ZBook-15-G2]

x-common-deploy-worker-2: &common_deploy_worker_2
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-server-2]

x-common-deploy-worker-3: &common_deploy_worker_3
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-server]

services:

  # MONITORING
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.prod.yml:/etc/prometheus/prometheus.yml
      - prometheus-prod-data:/prometheus
    networks:
      - dm_cluster_prod-fast
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      <<: *common_restart_policy
      placement:
        constraints: [node.hostname == dadaia-desktop]
        

  # VISUALIZATION
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - dm_cluster_prod-fast
    volumes:
      - grafana-prod-data:/var/lib/grafana
    <<: *common_deploy_master


  # MONITORING DOCKER SWARM CLUSTER ---> MASTER
  cadvisor_0:
    <<: *cadvisor_commons
    ports:
      - 28080:8080
    <<: *common_deploy_master

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 1
  cadvisor_1:
    <<: *cadvisor_commons
    ports:
      - 28081:8080
    <<: *common_deploy_worker_1

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 2
  cadvisor_2:
    <<: *cadvisor_commons
    ports:
      - 28082:8080
    <<: *common_deploy_worker_2

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 3
  cadvisor_3:
    <<: *cadvisor_commons
    ports:
      - 28083:8080
    <<: *common_deploy_worker_3


 

  # MONITORING SERVERS

  node_exporter_0:
    <<: *node_exporter_commons
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == dadaia-desktop]

  node_exporter_1:
    <<: *node_exporter_commons
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == dadaia-HP-ZBook-15-G2]

  node_exporter_2:
    <<: *node_exporter_commons
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == dadaia-server]

  node_exporter_3:
    <<: *node_exporter_commons
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == dadaia-server-2]



volumes:
  prometheus-prod-data:
  grafana-prod-data:

networks:
  dm_cluster_prod-fast:
    driver: overlay
