version: '3'

##########################################################################################
################    DEFAULT CONFIG FOR NODE EXPORTER AND CADVISOR    #####################

x-common-exporters-default: &node_exporter_commons
  image: quay.io/prometheus/node-exporter:latest
  command:
    - '--path.rootfs=/host'
  pid: host
  volumes:
    - '/:/host:ro,rslave'
  networks:
    - dm_cluster_prod_ops

x-common-cadvisor-default: &cadvisor_commons
  image: gcr.io/cadvisor/cadvisor:v0.44.1-test
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  command:
    - '--enable_metrics=advtcp,app,cpu,cpuLoad,cpu_topology,disk,diskIO,memory,memory_numa,network'

##########################################################################################
#########################    DEPLOYMENT CONFIGS FOR NODES    #############################

x-common-restart-default: &common_restart_policy
  restart_policy:
    condition: on-failure

x-common-deploy-master: &common_deploy_master
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-desktop]

x-common-deploy-worker-1: &common_deploy_worker_1
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-HP-ZBook-15-G2]

x-common-deploy-worker-2: &common_deploy_worker_2
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-server-2]

x-common-deploy-worker-3: &common_deploy_worker_3
  deploy:
    <<: *common_restart_policy
    placement:
      constraints: [node.hostname == dadaia-server]

##########################################################################################
################################    SERVICES CONFIG    ###################################

services:

  # PROMETHEUS UI -> http://192.168.15.101:9090
  prometheus:
    image: marcoaureliomenezes/dm-prometheus:1.0.0
    ports:
      - 9090:9090
    volumes:
      - prometheus_prod_data:/prometheus
    networks:
      - dm_cluster_prod_ops
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    <<: *common_deploy_master
        
  # GRAFANA UI -> http://192.168.15.101:13000
  grafana:
    image: grafana/grafana
    ports:
      - 13000:3000
    networks:
      - dm_cluster_prod_ops
    volumes:
      - grafana_prod_data:/var/lib/grafana
    <<: *common_deploy_master

  ########################################################################################
  #####################    MONITORING DOCKER SWARM CLUSTER    ############################

  cadvisor_master:
    <<: *cadvisor_commons
    ports:
      - 38080:8080
    <<: *common_deploy_master

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 1
  cadvisor_worker_1:
    <<: *cadvisor_commons
    ports:
      - 38081:8080
    <<: *common_deploy_worker_1

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 2
  cadvisor_worker_2:
    <<: *cadvisor_commons
    ports:
      - 38082:8080
    <<: *common_deploy_worker_2

  # MONITORING DOCKER SWARM CLUSTER ---> WORKER 3
  cadvisor_worker_3:
    <<: *cadvisor_commons
    ports:
      - 38083:8080
    <<: *common_deploy_worker_3

  ########################################################################################
  #####################    MONITORING SERVERS SWARM CLUSTER    ###########################

  node_exporter_master:
    <<: *node_exporter_commons
    networks:
      - dm_cluster_prod_ops
    <<: *common_deploy_master

  node_exporter_worker_1:
    <<: *node_exporter_commons
    networks:
      - dm_cluster_prod_ops
    <<: *common_deploy_worker_1

  node_exporter_worker_2:
    <<: *node_exporter_commons
    networks:
      - dm_cluster_prod_ops
    <<: *common_deploy_worker_2

  node_exporter_worker_3:
    <<: *node_exporter_commons
    networks:
      - dm_cluster_prod_ops
    <<: *common_deploy_worker_3

############################    END OF SERVICES CONFIG    ################################
##########################################################################################

volumes:
  prometheus_prod_data:
  grafana_prod_data:

networks:
  dm_cluster_prod_ops:
    driver: overlay
