version: '3'

##########################################################################################
################################    SERVICES CONFIG    ###################################

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./conf-prometheus-compose.yml:/etc/prometheus/prometheus.yml
      - prometheus-dev-data:/prometheus
    networks:
      - dm-operations-dev
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - dm-operations-dev
    volumes:
      - grafana-dev-data:/var/lib/grafana

  ########################################################################################
  ####################    MONITORING DOCKER SWARM CLUSTER    #############################
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.44.1-test
    container_name: cadvisor
    networks:
      - dm-operations-dev
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - '--enable_metrics=advtcp,app,cpu,cpuLoad,cpu_topology,disk,diskIO,memory,memory_numa,network'
    restart: unless-stopped

  ########################################################################################
  #######################    MONITORING LOCAL SERVER    ##################################

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    networks:
      - dm-operations-dev
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'

############################    END OF SERVICES CONFIG    ################################
##########################################################################################

volumes:
  prometheus-dev-data:
  grafana-dev-data:

networks:
  dm-operations-dev:
    driver: bridge
